server:
    port: ${PORT:7090}
spring:
    application:
        name: API-GATEWAY-SERVICE
    cloud:
        gateway:
            routes:
                -   id: APPLE-SERVICE-1
                    uri: http://localhost:7071
                    predicates:
                        - Path= /apple/api/v1/mobile**
                    filters:
                        - RewritePath=/(?<segment>.*)/api/v1/mobile, /api/v1/mobile
                -   id: ONEPLUS-SERVICE-1
                    uri: http://localhost:7072
                    predicates:
                        - Path= /oneplus/api/v1/mobile**
                    filters:
                        - RewritePath=/(?<segment>.*)/api/v1/mobile, /api/v1/mobile

# logging:
#     level:
#         org.springframework.cloud.gateway: DEBUG
